(* ::Package:: *)

(* Autogenerated Package *)

(* ::Section:: *)
(*SimpleDocs*)



(* ::Text:: *)
(*
	This implements the code behind the SimpleDocs stylesheet and palette, if I ever make a palette
*)



(* ::Subsubsection::Closed:: *)
(*Core Stuff*)



$NotebookTemplates::usage="";


(* ::Subsubsection::Closed:: *)
(*Project Stuff*)



$DocsProjects::usage="";
LoadProjectConfig::usage="";


(* ::Subsubsection::Closed:: *)
(*Notebooks*)



SetNotebookPaclet::usage="deprecated";
SetNotebookProject::usage="";
SaveNotebookToDocumentation::usage="";
SaveNotebookToPaclet::usage="deprecated";
SaveNotebookMarkdown::usage="";
SaveNotebookToProject::usage=""
SaveNotebookToPacletProject::usage="deprecated";
CheckSaveNotebook::usage="";


CreateTemplateNotebook::usage="";
SampleTemplateNotebook::usage="";


(* ::Subsubsection::Closed:: *)
(*GUI Elements*)



$InsertionMenu::usage="";
$HamburgerMenu::usage="";
$MetadataEditor::usage="";
$DockedCell::usage="";


(* ::Subsubsection::Closed:: *)
(*Docs*)



InitializeDocsSite::usage="";
BuildDocsSite::usage="";
BuildNotebookDocsSite::usage="";
OpenDocsSiteConfig::usage="";


(* ::Subsubsection::Closed:: *)
(*Paclets*)



SetPacletInfo::usage="";


Begin["`Private`"];


(* ::Subsection:: *)
(*Config*)



(* ::Text:: *)
(*
	Need to allow systems to customize their shiz. Might make sense to set up some kind of \[OpenCurlyDoubleQuote]project\[CloseCurlyDoubleQuote] system where that project can be a paclet or it can be standalone...
	This is a little messy right now, but the idea is to have a listing of \[OpenCurlyDoubleQuote]projects\[CloseCurlyDoubleQuote] that are currently being worked on. Each \[OpenCurlyDoubleQuote]project\[CloseCurlyDoubleQuote] has two core components, a project root directory and a config file. Neither is strictly necessary, but each is useful.
	Then all project property lookups can be done against the $DocsProject symbol allowing for centralization of options. This also can allow for batch building and things since we have a root directory.
	The other options I\[CloseCurlyQuote]m thinking will go here are:
		- Metadata: base metadata for all notebooks, when set metadata or whatever is clicked it\[CloseCurlyQuote]ll autofill any automatic values with values taken from here
		- BuildDirectory: a directory for building to outside of the default places. Might need two of these, one for the site, one for the basic documentation pages
		- MarkdownOptions: options to be sent to the Markdown converter so that they don\[CloseCurlyQuote]t have to be written into literally every page
	Each notebook will store what its parent project is (will need to implement some nice guessing/handling cloning notebooks of old ones so people do go insane doing this all the time). This will be Ensure loaded so that all the necessary properties exist to pull from.
*)



(* ::Subsubsection::Closed:: *)
(*$DocsProjects*)



If[!AssociationQ@$DocsProjects, $DocsProjects=<||>];


(* ::Subsubsection::Closed:: *)
(*getFileProject*)



possibleHeadPaths=
  {
    {"project", "docs", _},
    {"docs", _},
    {"docs"},
    {"Documentation", _, _}
    };


getFileProject[file_String]:=
  Module[
    {
      fsplit=FileNameSplit[file],
      drop
      },
    drop=
      SelectFirst[possibleHeadPaths, 
        MatchQ[fsplit, #~~Prepend~~__~~Append~~_]&, 
        None
        ];
    If[drop===None,
      FileBaseName@file,
      FileNameJoin@fsplit[[;;Length[drop]+1]]
      ]
    ]
    


(* ::Subsubsection::Closed:: *)
(*getFEFileDir*)



$standardPathStarters=
  Thread@Hold@
    {
      System`$TemporaryDirectory,
      PacletManager`$UserBasePacletsDirectory,System`$CacheBaseDirectory,
      System`$UserBaseDirectory,System`$UserAddOnsDirectory,
      System`$PreferencesDirectory,System`$LaunchDirectory,
      System`$UserDocumentsDirectory,System`$TopDirectory,
      System`$InstallationDirectory,PacletManager`$BasePacletsDirectory,
      System`$InitialDirectory,System`$HomeDirectory,
      System`$BaseDirectory,System`$AddOnsDirectory,System`$RootDirectory
      };


getFEFile[dirName_]:=
  Module[{starter, expDir=ExpandFileName@dirName, split},
    starter=
      SelectFirst[$standardPathStarters,
        StringStartsQ[expDir, ReleaseHold@#]&,
        None
        ];
    split=
      DeleteCases[""]@If[starter===None,
        FileNameSplit[expDir],
        FileNameSplit[StringTrim[expDir, ReleaseHold@starter]]
        ];
    If[starter===None,
      FrontEnd`FileName[Evaluate@split[[;;-2]], split[[-1]]],
      FrontEnd`FileName[
        Evaluate@
          Prepend[
            split[[;;-2]],
            starter
            ],
        Evaluate@split[[-1]]
        ]/.Hold[s_]:>s
      ]
    ]


(* ::Subsubsection::Closed:: *)
(*LoadProjectConfig*)



$defaultConfigPaths=
  {
    {"project", "docs", "Config.wl"},
    {"Config", "SimpleDocs", "Config.wl"},
    {"SimpleDocsConfig.wl"}
    };
LoadProjectConfig[projName_String, projDir_String, configFile_String]:=
  Module[
    {
      feFileDir,
      trueDir,
      trueConfig,
      props
      },
    trueDir=ToFileName@projDir;
    trueConfig=ToFileName@configFile;
    If[!TrueQ@Quiet@FileExistsQ@trueConfig,
      trueConfig=FileNameJoin@{trueDir, trueConfig}
      ];
    props=
      Association@
        Replace[Quiet@Get[trueConfig], Except[_?OptionQ|_Association]-><||>];
    feFileDir=getFEFile[trueDir];
    $DocsProjects[projName]=
      Association@
        Replace[Quiet@Get[configFile], Except[_?OptionQ|_Association]-><||>];
    If[DirectoryQ@projDir&&!KeyExistsQ[$DocsProjects[projName], "Directory"],
      $DocsProjects[projName, "Directory"]=feFileDir,
      If[!KeyExistsQ[$DocsProjects[projName], "Directory"],
        $DocsProjects[projName, "Directory"]=None
        ]
      ];
    If[!KeyExistsQ[$DocsProjects[projName], "ConfigFile"]&&FileExistsQ[configFile], 
      $DocsProjects[projName, "ConfigFile"]=
          getFEFile@
            StringTrim[ExpandFileName@configFile, ToFileName@feFileDir];
      If[!KeyExistsQ[$DocsProjects[projName], "ConfigFile"],
        $DocsProjects[projName, "ConfigFile"]=None
        ]
      ];
    projName
    ];
LoadProjectConfig[projName_String, projDir_, configFile_]:=
  LoadProjectConfig[projName, "", ""];
LoadProjectConfig[dir_String?DirectoryQ]:=
  LoadProjectConfig[
    cleanProjectBaseName@dir, 
    dir,
    SelectFirst[
      FileNameJoin@Prepend[#, dir]&/@
        $defaultConfigPaths,
      FileExistsQ,
      None
      ]
    ];


(* ::Subsubsection::Closed:: *)
(*ReloadProjectConfig*)



ReloadProjectConfig[proj_]:=
  Module[{a=$DocsProjects[proj]},
    $DocsProjects[proj]=
      Merge[
        {
          a,
          Association@
            Replace[
              Quiet@Get[Lookup[a, "ConfigFile"]], 
              Except[_?OptionQ|_Association]-><||>
              ]
          },
        Last
        ];
    ]


(* ::Subsubsection::Closed:: *)
(*cleanProjectBaseName*)



cleanProjectBaseName[name_]:=
  StringSplit[FileBaseName@name, "-"][[1]]


(* ::Subsubsection::Closed:: *)
(*projectQ*)



projectQ[projName_]:=
  KeyExistsQ[$DocsProjects, projName]||
    (DirectoryQ[projName]&&KeyExistsQ[$DocsProjects, cleanProjectBaseName@projName]);


(* ::Subsubsection::Closed:: *)
(*getProjectName*)



getProjectName[name_]:=
  Which[
    KeyExistsQ[$DocsProjects, name], 
      name,
    KeyExistsQ[$DocsProjects, cleanProjectBaseName@name],
      FileBaseName@name,
    True,
      None
    ]


(* ::Subsubsection::Closed:: *)
(*getProjectProp*)



getProjectProp[pname_, prop_, default_]:=
  Lookup[
    Lookup[$DocsProjects, pname, <||>],
    prop,
    default
    ]


(* ::Subsubsection::Closed:: *)
(*getProjectConfFile*)



getProjectConfFile[pname_]:=
  getProjectProp[pname, "ConfigFile", None]


(* ::Subsubsection::Closed:: *)
(*getProjectDir*)



getProjectDir[pname_]:=
  getProjectProp[pname, "Directory", None]


(* ::Subsubsection::Closed:: *)
(*getProjectPaclet*)



getProjectPaclet[pname_]:=
  Module[
    {
      pacName,
      dir
      },
    pacName=getProjectProp[pname, "Paclet", None];
    If[pacName===None,
      dir=getProjectDir@pname;
      If[PacletExecute["ValidDirectoryQ", dir], 
        PacletExecute["Paclet", dir],
        None
        ],
      PacletManager`PacletFind[pacName]
      ]
    ]


(* ::Subsubsection::Closed:: *)
(*getProjectPacletInfo*)



getProjectPacletInfo[pname_]:=
  Module[
    {
      pacName,
      dir
      },
    pacName=getProjectProp[pname, "Paclet", None];
    If[pacName===None,
      dir=getProjectDir@pname;
      If[PacletExecute["ValidDirectoryQ", dir], 
        PacletExecute["Association", dir],
        None
        ],
      PacletManager`PacletInformation[pacName]
      ]
    ]


(* ::Subsubsection::Closed:: *)
(*getProjectContext*)



getProjectContext[pname_]:=
  Module[
    {
      cont,
      pac,
      pi
      },
    cont=
      Lookup[
        getProjectProp[pname, "Metadata", {}],
        "context",
        None
        ];
    If[!StringQ@cont,
      pi=getProjectPacletInfo[pname];
      cont=First["Context"/.Append[pi, "Context"->{Lookup[pi, "Name"]<>"`"}]],
      ];
    cont
    ]


(* ::Subsubsection::Closed:: *)
(*getProjectBuildDir*)



getProjectBuildDir[pname_]:=
  getProjectProp[pname, "BuildDirectory", 
    getProjectDir@pname
    ]


(* ::Subsubsection::Closed:: *)
(*getProjectSitePath*)



getProjectSitePath[pname_]:=
  getProjectProp[pname, "SitePath", {"project", "docs"}]


(* ::Subsubsection::Closed:: *)
(*EnsureLoadProject*)



EnsureLoadProject[projName_, projDir_, projConf_]:=
  Module[{pname, pdir, pcnf},
    If[!projectQ[projName],
      If[!StringQ@projConf||StringLength[projConf]==0,
        pname=LoadProjectConfig[projName, projDir, None];
        pname=LoadProjectConfig[projName, projDir, projConf];
        ],
      pname=getProjectName[pname]
      ];
    {pname, getProjectDir[pname], getProjectConfFile[pname]}
    ];
EnsureLoadProject[nb_NotebookObject]:=
  EnsureLoadProject[
    CurrentValue[nb, {TaggingRules, "SimpleDocs", "Project", "Name"}],
    CurrentValue[nb, {TaggingRules, "SimpleDocs", "Project", "Directory"}],
    CurrentValue[nb, {TaggingRules, "SimpleDocs", "Project", "Config"}]
    ]


(* ::Subsection:: *)
(*Site*)



(* ::Subsubsection::Closed:: *)
(*docsSiteLoc*)



(* ::Subsubsubsection::Closed:: *)
(*Older*)



docsSiteLoc1//Clear
docsSiteLoc1[loc_String?(StringQ[#]&&StringLength[#]>0&&DirectoryQ[#]&)]:=
  FileNameJoin@{loc, "project", "docs"};
docsSiteLoc1[p_PacletManager`Paclet]:=
  docsSiteLoc1[p["Location"]];
docsSiteLoc1[s_String]:=
  Replace[PacletManager`PacletFind[s], {p_, ___}:>docsSiteLoc1[p]];


(* ::Subsubsubsection::Closed:: *)
(*Newer*)



docsSiteLoc[projName_]:=
  FileNameJoin@Flatten@{
    getProjBuildDir@projName, 
    getProjectSitePath@projName
    }


(* ::Subsubsection::Closed:: *)
(*InitializeDocsSite*)



InitializeDocsSite[proj_]:=
  With[{l=docsSiteLoc[proj]},
    If[StringQ@l&&!DirectoryQ@l,
      With[{s=Ems["New", l, "docs"]},
        DeleteFile/@FileNames["*", FileNameJoin@{s, "content", "ref"}];
        DeleteFile/@FileNames["*", FileNameJoin@{s, "content", "guide"}];
        s
        ],
      $Failed
      ]
    ]


(* ::Subsubsection::Closed:: *)
(*BuildDocsSite*)



BuildDocsSite[loc_]:=
  Ems["Build", docsSiteLoc[loc]];


(* ::Subsubsection::Closed:: *)
(*BuildNotebookDocsSite*)



(* ::Subsubsubsection::Closed:: *)
(*BuildNotebookDocsSite*)



BuildNotebookDocsSite[nb_, ploc_:Automatic]:=
  With[{pac=getNotebookPaclet[nb, ploc]},
    If[pac=!=None,
      buildNotebookDocsSite[pac]
      ]
    ]


(* ::Subsubsubsection::Closed:: *)
(*overrideMonitor*)



overrideMonitor//Clear


overrideMonitor[expr_, sym_]:=
  Block[{Monitor},
    SetAttributes[Monitor, HoldAllComplete];
    Monitor[a_, b_, ___]:=
      (
        sym=b;
        a
        );
    expr;
    ];
overrideMonitor~SetAttributes~HoldAll;


(* ::Subsubsubsection::Closed:: *)
(*buildNotebookDocsSite*)



$protector=False;


buildNotebookDocsSite[loc_]:=
  With[{l=docsSiteLoc[loc]},
    Block[{blech},
      If[DirectoryQ@l,
        Module[{nb},
          nb=
            MessageDialog[
              Column@{
                StringForm[
                  "Creating site @ ``", l
                  ],
                Panel[
                  Dynamic[
                    If[MatchQ[blech, _Symbol], "", blech],
                    TrackedSymbols:>{blech}
                    ],
                  ImageSize->{350, 100}
                  ]
                },
              WindowTitle->"Building Site",
              WindowFloating->True
              ];
          overrideMonitor[
            PySimpleServerOpen@
              Ems["Build", l],
            blech
            ];
          NotebookClose@nb;
          ],
        $Failed
        ]
      ]
    ]


(* ::Subsubsection::Closed:: *)
(*OpenDocsSiteConfig*)



OpenDocsSiteConfig[nb_, ploc_:Automatic]:=
  SystemOpen@
    FileNameJoin@{docsSiteLoc@getNotebookPaclet[nb, ploc], "SiteConfig.wl"}


(* ::Subsection:: *)
(*Misc*)



(* ::Subsubsection::Closed:: *)
(*$MetadataMap*)



$MetadataMap=
  <|
    "Basics"->
      {
        "Context","Language","Paclet",
        "Type","Label","URI",
        "Summary","Status",
        "Title","Title Modifier","Window Title"
        },
    "Location"->
      {"Keywords","Synonyms","Index"},
    "History"->{"Built","History"},
    "Advanced"->{"Table Tags","Tutorial Collection Links","Special Keywords"}
    |>;


(* ::Subsubsection::Closed:: *)
(*$NotebookTemplates*)



(* ::Subsubsubsection::Closed:: *)
(*$miscTemplates*)



$miscTemplates=
  <|
    "TitleBar"->Cell["<Context>", "TitleBar"],
    "Divider"->Cell["", "PageBreak", PageBreakBelow->False, PageBreakAbove->False],
    "Footer"->Cell["Made with SimpleDocs", "Text", "Footer"]
    |>;


(* ::Subsubsubsection::Closed:: *)
(*$baseTemplates*)



$baseTemplates=
  <|
    "Usage"->
      Cell@
        CellGroupData[
          {
            Cell[BoxData@RowBox[{"<FunctionName>","[",RowBox[{"arg1", ",",  "arg2", ",",  "..."}],"]"}], "Code", "UsageInput"],
            Cell["description", "Text", "UsageText"]
            }
          ],
    "Guide Line"->
      Cell[
        TextData@{
          ButtonBox["Function1", BaseStyle->"Link",ButtonData->"paclet:Pkg/ref/Function1"], 
          " - ", 
          "description"
          }, "Text"],
    "Details"->
      Cell@
        CellGroupData[
          {
            Cell["Details item", "Item", "DetailsItem"],
            Cell["Details subitem", "Subitem", "DetailsSubitem"]
            }
          ],
    "Example"->
      Cell@
        CellGroupData[
          {
            Cell["Description", "Text"],
            Cell[BoxData@RowBox[{"FunctionName","[",RowBox[{"arg1",",", "arg2", ",", "..."}],"]"}], "Code"],
            Cell[BoxData[RowBox[{"result"}]], "Output", GeneratedCell->True]
            }
          ],
    "Related Functions"->
      Cell@
        CellGroupData[
          {
            Cell["See Also", "Subsection", "SeeAlso"],
            Cell[
              TextData@
                {
                  ButtonBox["Function1",
                    BaseStyle->{"Link", "Input"},ButtonData->"paclet:Pkg/ref/Function1"]," | ",
                  ButtonBox["Function2",
                    BaseStyle->{"Link", "Input"},ButtonData->"paclet:Pkg/ref/Function2"]
                  },
               "Text"
              ]
            }
          ],
    "Related Guides"->
      Cell@
        CellGroupData[
          {
            Cell["Related Guides", "Subsection", "Related"],
            Cell[
              TextData@ButtonBox["Guide 1",BaseStyle->"Link",ButtonData->"paclet:Pkg/guide/Guide1"],
              "Item"
              ],
            Cell[
              TextData@ButtonBox["Guide 2",BaseStyle->"Link",ButtonData->"paclet:Pkg/guide/Guide2"],
              "Item"
              ]
            }
          ],
    "Related Links"->
      Cell@
        CellGroupData[
          {
            Cell["Related Links", "Subsection", "RelatedLinks"],
            Cell[
              TextData@
                ButtonBox[
                  "Link 1",
                  BaseStyle->"Hyperlink",
                  ButtonData->{URL["https://google.com"],
                      None},
                  ButtonNote->"Link 1"
                  ],
              "Item"
              ],
            Cell[
              TextData@
                ButtonBox[
                  "Link 2",
                  BaseStyle->"Hyperlink",
                  ButtonData->{URL["https://paclets.github.io/PacletServer"],
                      None},
                  ButtonNote->"Link 2"
                  ],
              "Item"
              ]
            }
          ]
    |>;


(* ::Subsubsubsection::Closed:: *)
(*$sectionTemplates*)



$sectionTemplates=
  <|
    "Usage Section":>
      Cell@
        CellGroupData[
          {
            Cell["", "Subsection", "UsageSection"],
            $baseTemplates["Usage"],
            Cell["", "UsageSectionFooter"]
            }
          ],
    "Details Section":>
      Cell@
        CellGroupData[
          {
            Cell["Details", "Subsection", "DetailsSection"],
            $baseTemplates["Details"]
            },
          Closed
          ],
    "Examples Section":>
      Cell@
        CellGroupData[
          {
            Cell["Examples", "Subsection", "ExamplesSection"],
            Cell@
              CellGroupData[{
                  Cell["Basic Examples", "Subsubsection", "ExamplesSubsection"],
                  $baseTemplates["Example"]
                  }]
            }
          ],
    "Related Section":>
      Cell@
        CellGroupData[
          {
            $baseTemplates["Related Functions"],
            $baseTemplates["Related Guides"],
            $baseTemplates["Related Links"]
            }
          ],
    "Guide Section":>
      Cell@
        CellGroupData[
          {
            $miscTemplates["Divider"],
            Cell["Description", "Text"],
            $baseTemplates["Guide Line"],
            $baseTemplates["Guide Line"]
            }
          ]
    |>;


(* ::Subsubsubsection::Closed:: *)
(*$metaCell*)



$metaCell=
  Cell[
    BoxData[
      RowBox[{
          RowBox[{"(*"," ",
              RowBox[{"Markdown"," ","metadata"}]," ","*)"}],"\[IndentingNewLine]",
          RowBox[{"<|","\[IndentingNewLine]",
              RowBox[{
                  RowBox[{"\"Date\"","\[RuleDelayed]","Now"}],",","\[IndentingNewLine]",
                  RowBox[{"\"ExportOptions\"","\[Rule]",
                      RowBox[{"{","\[IndentingNewLine]",
                          RowBox[{"(*",
                              RowBox[{"\"UseImageInput\"","\[Rule]","True"}],"*)"}],"\[IndentingNewLine]","}"
                          }]
                      }]
                  }],"\[IndentingNewLine]",
              "|>"
              }]
          }]
      ],
    "Metadata"];


(* ::Subsubsubsection::Closed:: *)
(*$primaryTemplates*)



$primaryTemplates=
  <|
    "Symbol"->
      Cell@
        CellGroupData[
          {
            $metaCell,
            $miscTemplates["TitleBar"],
            Cell["FunctionName", "Section"],
            $sectionTemplates["Usage Section"],
            $sectionTemplates["Details Section"],
            $sectionTemplates["Examples Section"],
            $sectionTemplates["Related Section"],
            $miscTemplates["Footer"]
            }
          ],
    "Guide"->
      Cell@
        CellGroupData[
          {
            $metaCell,
            $miscTemplates["TitleBar"],
            Cell["Guide Name", "Section"],
            Cell["guide descriptions", "Text"],
            $sectionTemplates["Guide Section"],
            $miscTemplates["Divider"],
            $baseTemplates["Related Guides"],
            $baseTemplates["Related Links"],
            $miscTemplates["Footer"]
            }
          ],
    "Tutorial"->
      Cell@
        CellGroupData[
          {
            $metaCell,
            $miscTemplates["TitleBar"],
            Cell["Tutorial Name", "Section"],
            $miscTemplates["Footer"]
            }
          ]
    |>;


(* ::Subsubsubsection::Closed:: *)
(*$NotebookTemplates*)



$NotebookTemplates=
  Join[
    $primaryTemplates,
    $sectionTemplates,
    $baseTemplates,
    $miscTemplates
    ]


(* ::Subsection:: *)
(*Notebook*)



(* ::Subsubsection::Closed:: *)
(*getMeta*)



getMeta[nb_, k_]:=
  CurrentValue[nb, {TaggingRules, "Metadata", ToLowerCase@k}];


(* ::Subsubsection::Closed:: *)
(*setMeta*)



getMeta[nb_, k_, v_]:=
  CurrentValue[nb, {TaggingRules, "Metadata", ToLowerCase@k}]=v;


(* ::Subsubsection::Closed:: *)
(*getProjectDialog*)



getProjectDialog[]:=
  DialogInput[
    {
      projName="",
      projDir="",
      projConf=""
      },
    Pane[
      Panel[
        Column[
          {
            EventHandler[
              InputField[Dynamic[projName],
                String,
                BoxID->"pname",
                FieldHint->"project name"
                ],
              "ReturnKeyDown":>DialogReturn@{projName, projDir, projConf}
              ],
            EventHandler[
              InputField[Dynamic[projConf],
                String,
                BoxID->"conf",
                FieldHint->"project directory (optional)"
                ],
              "ReturnKeyDown":>DialogReturn@{projName, projDir, projConf}
              ],
            EventHandler[
              InputField[Dynamic[projConf],
                String,
                BoxID->"conf",
                FieldHint->"config file/relative path (optional)"
                ],
              "ReturnKeyDown":>DialogReturn@{projName, projDir, projConf}
              ],
            DefaultButton[DialogReturn@{projName, projDir, projConf}]
            }
          ],
        "Specify project:",
        ImageSize->{Automatic, 120},
        Alignment->Center
        ],
      ImageSize->{250, 150},
      Alignment->Center
      ],
    NotebookDynamicExpression:>
      Refresh[
        FrontEndExecute@FrontEnd`MoveCursorToInputField[EvaluationNotebook[], "pname"], 
        None
        ],
CellInsertionPointCell->Automatic
    ];


(* ::Subsubsection::Closed:: *)
(*getPacletDialog*)



getPacletDialog[]:=
  DialogInput[
    {pacletName=""},
    Pane[
      Panel[
        Column[
          {
            EventHandler[
              InputField[Dynamic@pacletName,
                String,
                BoxID->"pname",
                FieldHint->"paclet name"
                ],
              "ReturnKeyDown":>DialogReturn@pacletName
              ],
            DefaultButton[DialogReturn@pacletName]
            }
          ],
        "Specify paclet:",
        ImageSize->{Automatic, 80},
        Alignment->Center
        ],
      ImageSize->{250, 100},
      Alignment->Center
      ],
    NotebookDynamicExpression:>
      Refresh[
        FrontEndExecute@FrontEnd`MoveCursorToInputField[EvaluationNotebook[], "pname"], 
        None
        ],
CellInsertionPointCell->Automatic
    ];


(* ::Subsubsection::Closed:: *)
(*getNBPaclet*)



getNBPaclet[nb_]:=
  CurrentValue[nb,
  {TaggingRules, "SimpleDocs", "Paclet"},
  CurrentValue[nb, {TaggingRules, "Paclet"}]
  ]


(* ::Subsubsection::Closed:: *)
(*getNBProject*)



getNBProject[nb_]:=
  CurrentValue[nb,
  {TaggingRules, "SimpleDocs", "Project", "Name"},
  getNBPaclet[nb]
  ]


(* ::Subsubsection::Closed:: *)
(*getNBProjName*)



(* ::Text:: *)
(*
	Might need a few updates...
*)



getNBProjName[nb_, proj_]:=
  Module[
    {
      projName=proj
      },
    If[!projectQ@projName, 
      projName=getNBProject[nb]
      ];
    EnsureLoadProject[nb];
    If[!projectQ[projName], 
      projName=SetNotebookProject[nb];
      ];
    EnsureLoadProject[nb];
    projName
    ];


(* ::Subsubsection::Closed:: *)
(*SetNotebookProject*)



SetNotebookProject[nb_, auto:True|False:False]:=
  Module[
    {
      projLoc=If[auto, Quiet@getFileProject[NotebookFileName[nb]]],
      projConf,
      projName
      },
    If[!StringQ@projLoc,
      {projName, projLoc, projConf}=getProjectDialog[nb]
      ];
    {projName, projLoc, projConf}=
      EnsureLoadProject[projName, projLoc, projConf];
    CurrentValue[nb, {TaggingRules, "SimpleDocs", "Project", "Name"}]=projName;
    CurrentValue[nb, {TaggingRules, "SimpleDocs", "Project", "Directory"}]=projLoc;
    CurrentValue[nb, {TaggingRules, "SimpleDocs", "Project", "Config"}]=projConf;
    projName
    ]


(* ::Subsubsection::Closed:: *)
(*SetNotebookPaclet*)



SetNotebookPaclet[nb_]:=
  Module[
    {pacletLoc=getPacletDialog[]},
    If[StringLength@pacletLoc>0,
      CurrentValue[nb, {TaggingRules, "SimpleDocs", "Paclet"}]=pacletLoc,
      pacletLoc=None
      ];
    pacletLoc
    ]


(* ::Subsubsection::Closed:: *)
(*getPacletDocsTypePath*)



getPacletDocsTypePath[proj_, type_]:=
  Lookup[
      <|
        "symbol"->FileNameJoin@{"ReferencePages", "Symbols"}, 
        "Symbol"->FileNameJoin@{"ReferencePages", "Symbols"}
        |>, 
      type,
      If[StringQ@type,
        Replace[
          (ToUpperCase[StringTake[#, {1}]]<>ToLowerCase@StringDrop[#, 1])&@ type<>"s", 
          s:Except["Guides"|"Tutorials"]:>
            FileNameJoin@{"ReferencePages", s}
          ],
        FileNameJoin@{"ReferencePages", "Symbols"}
        ]
      ]


(* ::Subsubsection::Closed:: *)
(*getPacletDocsLangPath*)



getPacletDocsLangPath[proj_, lang_]:=
  lang


(* ::Subsubsection::Closed:: *)
(*getPacletDocsExt*)



getPacletDocsExt[proj_, ext_]:=
  ext


(* ::Subsubsection::Closed:: *)
(*getPacletSaveLocation*)



(* ::Subsubsubsection::Closed:: *)
(*Older*)



getPacletSaveLocation1[loc_String, lang_, type_]:=
  FileNameJoin@{
    loc, 
    "Documentation", 
    lang, 
    Lookup[
      <|
        "symbol"->FileNameJoin@{"ReferencePages", "Symbols"}, 
        "Symbol"->FileNameJoin@{"ReferencePages", "Symbols"}
        |>, 
      type,
      If[StringQ@type,
        Replace[
          (ToUpperCase[StringTake[#, {1}]]<>ToLowerCase@StringDrop[#, 1])&@ type<>"s", 
          s:Except["Guides"|"Tutorials"]:>
            FileNameJoin@{"ReferencePages", s}
          ],
        FileNameJoin@{"ReferencePages", "Symbols"}
        ]
      ]
    };
getPacletSaveLocation1[pac_PacletManager`Paclet, lang_, type_]:=
  getPacletSaveLocation1[pac["Location"], lang, type];


(* ::Subsubsubsection::Closed:: *)
(*Newer*)



getPacletSaveLocation[projName_String, lang_, type_]:=
  FileNameJoin@Flatten@{
    getProjectProp[projName, "BuildDirectory", 
      getProjectDir@projName
      ], 
    getPacletDocsExt[projName, "Documentation"], 
    getPacletDocsLangPath[projName, lang], 
    getPacletDocsTypePath[projName, type]
    };


(* ::Subsubsection::Closed:: *)
(*getPacletSaveFileName*)



getPacletSaveFileName[pac_, nb_]:=
  Module[
    {
      cont,
      lang,
      type,
      baseDir,
      title,
      pi
      },
    cont=getMeta[nb, "context"];
    lang=getMeta[nb, "language"];
    If[cont===Automatic,
      pi=PacletManager`PacletInformation[pac];
      setMeta[nb, "context", 
        First["Context"/.Append[pi, "Context"->{Lookup[pi, "Name"]<>"`"}]]
        ]
      ];
    type=getMeta[nb, "type"];
    lang=Lookup[<|"en"->"English"|>, lang, $Language];
    baseDir=getPacletSaveLocation[pac, lang, type];
    Quiet@CreateDirectory[baseDir, CreateIntermediateDirectories->True];
    title=CurrentValue[nb, {TaggingRules, "Metadata", "label"}];
    If[!StringQ@title, title="Symbol"];
    FileNameJoin@{baseDir,StringTrim[title, ".nb"]<>".nb" }
    ];


(* ::Subsubsection::Closed:: *)
(*getSiteTypeExt*)



getSiteTypeExt[proj_, type_]:=
  StringTrim[
    Lookup[<|"symbol"->"ref", "Symbol"->"ref"|>, type,
      If[StringQ@type,
        (ToUpperCase[StringTake[#, {1}]]<>StringDrop[#, 1])&@ type, 
        "ref"
        ]
      ],
    "s"~~EndOfString
    ]


(* ::Subsubsection::Closed:: *)
(*getSiteContentExt*)



getSiteContentExt[proj_, ext_]:=
  ext


(* ::Subsubsection::Closed:: *)
(*getSiteSaveLocation*)



(* ::Subsubsubsection::Closed:: *)
(*Older*)



getSiteSaveLocation1[loc_, type_]:=
  FileNameJoin@{
    docsSiteLoc@loc, 
    "content",
    StringTrim[
      Lookup[<|"symbol"->"ref", "Symbol"->"ref"|>, type,
        If[StringQ@type,
          (ToUpperCase[StringTake[#, {1}]]<>StringDrop[#, 1])&@ type, 
          "ref"
          ]
        ],
      "s"~~EndOfString
      ]
    };


(* ::Subsubsubsection::Closed:: *)
(*Newer*)



getSiteSaveLocation[projName_, type_]:=
  FileNameJoin@Flatten@{
    docsSiteLoc@projName, 
    getSiteContentExt[projName, "content"],
    getSiteTypeExt[projName, type]
    };


(* ::Subsubsection::Closed:: *)
(*getSiteSaveFileName*)



(* ::Subsubsubsection::Closed:: *)
(*older*)



getSiteSaveFileName1[pac_, nb_]:=
  Module[
    {
      cont,
      lang,
      type,
      baseDir,
      title,
      pi
      },
    cont=getMeta[nb, "context"];
    lang=getMeta[nb, "language"];
    If[cont===Automatic,
      pi=PacletManager`PacletInformation[pac];
      setMeta[nb, "context",
        First["Context"/.Append[pi, "Context"->{Lookup[pi, "Name"]<>"`"}]]
        ]
      ];
    type=getMeta[nb, "type"];
    InitializeDocsSite[pac];
    baseDir=getSiteSaveLocation[pac, type];
    title=CurrentValue[nb, {TaggingRules, "Metadata", "label"}];
    If[!StringQ@title, title="Symbol"];
    Quiet@CreateDirectory[baseDir, CreateIntermediateDirectories->True];
    FileNameJoin@{baseDir,StringTrim[title, ".nb"]<>".nb" }
    ];


(* ::Subsubsubsection::Closed:: *)
(*newer*)



getSiteSaveFileName[projName_, nb_]:=
  Module[
    {
      cont,
      lang,
      type,
      baseDir,
      title,
      pi,
      projDir,
      pac
      },
    cont=getMeta[nb, "context"];
    lang=getMeta[nb, "language"];
    If[cont===Automatic,
      setMeta[nb, "context", getProjectContext[projName]]
      ];
    type=getMeta[nb, "type"];
    InitializeDocsSite[projName];
    baseDir=getSiteSaveLocation[projName, type];
    title=CurrentValue[nb, {TaggingRules, "Metadata", "label"}];
    If[!StringQ@title, title="Symbol"];
    Quiet@CreateDirectory[baseDir, CreateIntermediateDirectories->True];
    FileNameJoin@{baseDir,StringTrim[title, ".nb"]<>".nb" }
    ];


(* ::Subsubsection::Closed:: *)
(*getNotebookPaclet*)



getNotebookPaclet[nb_, ploc_:Automatic]:=
  Module[
    {
      pacletLoc=ploc,
      pac
      },
    If[!StringQ@pacletLoc, 
      pacletLoc=getNBPaclet[nb]
      ];
    If[!StringQ[pacletLoc], 
      pacletLoc=SetNotebookPaclet[nb];
      ];
    If[StringQ@pacletLoc,
      pac=PacletManager`PacletFind[pacletLoc];
      If[Length@pac>0, pac=First@pac, pac=None],
      pac=None
      ];
    pac
    ]


(* ::Subsubsection::Closed:: *)
(*prepNotebookForDocs*)



(* ::Text:: *)
(*
	For now we\[CloseCurlyQuote]re just going to assume we only go up one level before finding the docs notebook
*)



prepNotebookForDocs[nb_]:=
  Notebook[#[[1]],
    FilterRules[
      Flatten@{
        List@@#[[2;;]], 
        ScreenStyleEnvironment->"Working",
        StyleDefinitions->
          Notebook[
            {
              Cell[
                StyleData[
                  StyleDefinitions->
                    FrontEnd`FileName[{"SimpleDocs"}, "SimpleDocs.nb"]
                  ]
                ],
              Cell[
                StyleData[
                  StyleDefinitions->
                    FrontEnd`FileName[{ParentDirectory[]}, "SimpleDocsStyles.nb"]
                  ]
                ],
              Cell[
                StyleData[
                  StyleDefinitions->
                    FrontEnd`FileName[{ParentDirectory[], ParentDirectory[]}, "SimpleDocsStyles.nb"]
                  ]
                ],
              Cell[StyleData[StyleDefinitions->"Default.nb"]]
              },
            StyleDefinitions->"PrivateStylesheetFormatting.nb"
            ]
        },
       Except[ScreenStyleEnvironment|StyleDefinitions]
      ]
    ]&@NotebookGet[nb]


(* ::Subsubsection::Closed:: *)
(*SaveNotebookToDocumentation*)



(* ::Text:: *)
(*
	New version of SaveNotebookToPaclet that makes use of the more flexible project structure
*)



SaveNotebookToDocumentation//Clear;
SaveNotebookToDocumentation[nb_, proj_:Automatic]:=
  Module[
    {
      projName=proj,
      projDir,
      projConf,
      fname
      },
    projName=getNBProjectName[nb, projName];
    fname=getPacletSaveFileName[projName, nb];
    If[StringQ@fname&&DirectoryQ@DirectoryName@fname,
      CopyFile[
        PackageFilePath["FrontEnd", "StyleSheets", "SimpleDocs", "SimpleDocs.nb"],
        FileNameJoin@{
          Nest[DirectoryName, fname, 2],
          "SimpleDocsStyles.nb"
          }
        ];
      Export[fname, prepNotebookForDocs[nb]]
      ]
    ]


(* ::Subsubsection::Closed:: *)
(*SaveNotebookToProject*)



(* ::Text:: *)
(*
	New version of SaveNotebookToPacletProject that makes use of the more flexible project structure
*)



SaveNotebookToProject//Clear
SaveNotebookToProject[nb_, proj_:Automatic]:=
  Module[
    {
      projName=proj,
      pac,
      fname
      },
    projName=getNBProjectName[nb, projName];
    fname=getSiteSaveFileName[projName, nb];
    If[StringQ@fname&&DirectoryQ@DirectoryName@fname,
      NotebookSave[nb, fname]
      ]
    ]


(* ::Subsubsection::Closed:: *)
(*SaveNotebookToPaclet*)



SaveNotebookToPaclet//Clear;
SaveNotebookToPaclet[nb_, ploc_:Automatic]:=
  Module[
    {
      pacletLoc=ploc,
      pac,
      fname
      },
    If[!StringQ@pacletLoc, 
      pacletLoc=getNBPaclet[nb]
      ];
    If[!StringQ[pacletLoc], 
      pacletLoc=SetNotebookPaclet[nb];
      ];
    If[StringQ@pacletLoc,
      pac=PacletManager`PacletFind[pacletLoc];
      If[Length@pac>0, pac=First@pac, pac=None];
      If[pac=!=None,
        fname=getPacletSaveFileName[pac, nb];
        Export[
          fname,
          Notebook[#[[1]],
            FilterRules[
              Flatten@{List@@#[[2;;]], ScreenStyleEnvironment->"Working"},
               Except[ScreenStyleEnvironment]
              ]
            ]&@NotebookGet[nb] 
          ]
        ]
      ]
    ]


(* ::Subsubsection::Closed:: *)
(*SaveNotebookToPacletProject*)



SaveNotebookToPacletProject//Clear
SaveNotebookToPacletProject[nb_, ploc_:Automatic]:=
  Module[
    {
      pacletLoc=ploc,
      pac,
      fname
      },
    If[!StringQ@pacletLoc, 
      pacletLoc=getNBPaclet[nb]
      ];
    If[!StringQ[pacletLoc], 
      pacletLoc=SetNotebookPaclet[nb];
      ];
    If[StringQ@pacletLoc,
      pac=PacletManager`PacletFind[pacletLoc];
      If[Length@pac>0, pac=First@pac, pac=None];
      If[pac=!=None,
        fname=getSiteSaveFileName[pac, nb];
        NotebookSave[nb, fname]
        ]
      ]
    ]


(* ::Subsubsection::Closed:: *)
(*SaveNotebookMarkdown*)



(* ::Subsubsubsection::Closed:: *)
(*customMDExporter*)



customMDExporter//Clear
customMDExporter[pi_, c:Cell[_, "Text", "Footer", ___]]:=
  {
    Cell["", "PageBreak"],
    c
    };
customMDExporter[pi_, e_]:=e


(* ::Subsubsubsection::Closed:: *)
(*mergeCellStyles*)



mergeCellStyles[md_]:=
  Module[
    {
      sub=
        Lookup[Select[Lookup[md, "ExportOptions", {}], OptionQ], "CellStyles", {}],
      autof
      },
    autof=Lookup[sub, Automatic, None];
    {ParentList, 
      "Input", 
      Automatic->
        If[autof===None, 
          customMDExporter,
          customMDExporter[#, autof[##]]&
          ]
      }
    ]


(* ::Subsubsubsection::Closed:: *)
(*SaveNotebookMarkdown*)



SaveNotebookMarkdown[nb_]:=
  Module[
    {
      md=MarkdownNotebookMetadata@nb,
      projName=getNBProjectName[nb, None]
      (* for some reason this isn't getting linked in properly... *)
      },
    md=
      Merge[
        {
          Replace[md,
            ("CellStyles"->_)->Nothing,
            4
            ],
          "ExportOptions"->
            {
              "PacletLinkResolutionFunction"->
                Function[l, 
                  "../"<>
                  URLBuild[
                    Join@@
                      SplitBy[
                        URLParse[l, "Path"],
                        #=="ref"||#=="guide"||#=="tutorial"&
                        ][[-2;;]]
                    ]<>".html"
                  ],
              "CellStyles"->mergeCellStyles[md],
              "ContentPathExtension"->".."
              },
          "Title"->getMeta[nb, "title"],
          "Date"->
            Replace[getMeta[nb, "built"], 
              {
                s_String:>DateObject@ToExpression[s],
                l_List:>DateObject[l]
                }
              ],
          getProjectProp[projName, "MarkdownOptions", {}],
          Flatten@{
              Replace[
                CurrentValue[nb, {TaggingRules, "Metadata"}],
                Except[_?OptionQ]:>{}
                ]
              }
          },
        Which[
          AllTrue[#, OptionQ], 
            Normal@Merge[#, First],
          AllTrue[#, ListQ],
            Join@@#,
          Length@#==1,
            First@#,
          ListQ@#[[2]],
            Prepend[#[[2]], #[[1]]],
          True,
            First@#
          ]&
        ];
  NotebookMarkdownSave[nb, Sequence@@Normal@md]
  ]


(* ::Subsubsection::Closed:: *)
(*PrepareNotebookMetadata*)



PrepareNotebookMetadata[nb_]:=
  Module[
    {
      projName,
      baseData
      },
    projName=getNBProjName[nb];
    baseData=
      getProjectProp[projName, "Metadata", <||>];
    Normal@
      Merge[
        {
          DocMetadata[nb],
          baseData
          },
        Last
        ]
    ]


(* ::Subsubsection::Closed:: *)
(*PopulateNotebookMetadata*)



capitalize=ToUpperCase[StringTake[#, {1}]]<>StringDrop[#, 1]&


PopulateNotebookMetadata[nb_]:=
  Module[{md=PrepareNotebookMetadata},
    CurrentValue[nb, {TaggingRules, "Metadata"}]=md;
    CurrentValue[nb, {TaggingRules, "ColorType"}]=
      capitalize[Lookup[md, "type", "message"]]<>"Color";
    ]


(* ::Subsubsection::Closed:: *)
(*ClearNotebookMetadata*)



ClearNotebookMetadata[nb_]:=
  CurrentValue[nb, {TaggingRules, "Metadata"}]=
      Thread[Map[ToLowerCase, Flatten@Values@$MetadataMap]->Automatic];


(* ::Subsubsection::Closed:: *)
(*CheckSaveNotebook*)



CheckSaveNotebook[nb_]:=
  Module[
    {
      saveMD,
      saveDoc
      },
    saveMD=
      CurrentValue[nb, {TaggingRules, "SimpleDocs", "MarkdownAutosave"}, False];
    saveDoc=
      CurrentValue[nb, {TaggingRules, "SimpleDocs", "DocumentationAutosave"}, False];
    If[TrueQ@saveDoc,
      SaveNotebookToPaclet[nb]
      ];
    If[TrueQ@saveMD,
      SaveNotebookMarkdown[nb]
      ];
    ]


(* ::Subsection:: *)
(*Templates*)



(* ::Subsubsection::Closed:: *)
(*CreateTemplateNotebook*)



$ctnMap=
  <|
    "Symbol"->SymbolNotebookTemplate,
    "Guide"->GuideNotebookTemplate,
    "Tutorial"->TutorialNotebookTemplate
    |>;


CreateTemplateNotebook//ClearAll


CreateTemplateNotebook[type:(Alternatives@@Keys[$ctnMap]), thing_]:=
  CreateDocument@Lookup[$ctnMap, type][thing];
CreateTemplateNotebook[thing_Symbol]:=
  CreateTemplateNotebook["Symbol", thing];
CreateTemplateNotebook[thing_String]:=
  If[NameQ[thing],
    ToExpression[thing, StandardForm,
      Function[Null, CreateTemplateNotebook["Symbol", #], HoldAllComplete]
      ],
    CreateTemplateNotebook["Guide", thing]
    ];
CreateTemplateNotebook[e_]:=
  CreateTemplateNotebook[Evaluate@e]/;
    MatchQ[e, _String|_Symbol];
CreateTemplateNotebook[type_, thing_]:=
  CreateTemplateNotebook[Evaluate@type, thing]/;
    KeyExistsQ[$ctnMap, type];
CreateTemplateNotebook~SetAttributes~HoldAll;


PackageAddAutocompletions[
  CreateTemplateNotebook,
  {Keys@$ctnMap}
  ]


(* ::Subsubsection::Closed:: *)
(*SymbolNotebookTemplate*)



(* ::Subsubsubsection::Closed:: *)
(*formatUsageSection*)



formatUsageSection[u_]:=
  Cell@
    CellGroupData[Flatten@{
      Cell["", "UsageSection"],
      Replace[u,
        {a_, b_}:>
          {
            Cell[
              BoxData@FrontEndExecute@FrontEnd`ReparseBoxStructurePacket[a], 
              "Code", 
              "UsageInput"
              ],
            Cell[
              b, 
              "Text", 
              "UsageText"
              ]
              },
        1
        ],
      Cell["", "UsageSectionFooter"]
      }]


(* ::Subsubsubsection::Closed:: *)
(*formatDetailsSection*)



formatDetailsSection[deets_]:=
  Cell@
    CellGroupData[
      Prepend[Cell["Details", "Subsection", "DetailsSection"]]@
        Replace[
          deets,
          {
            grid:{__List}:>
              Sequence@@Replace[grid,
                {
                  {a_}:>Cell[a, "Subitem", "DetailsItem"],
                  {a_, b_}:>
                    Sequence@@{
                      Cell[a, "Subitem", "DetailsItem"],
                      Cell[b, "Subsubitem", "DetailsItem"]
                      }
                  },
                1
                ],
            line_:>Cell[StringRiffle[line], "Item", "DetailsItem"]
            },
          1
          ],
      Closed
      ]


(* ::Subsubsubsection::Closed:: *)
(*formatExamplesSection*)



formatExamplesSection[ex_, d_:0]:=
  Module[{dooooop=True},
    If[d==0,
      Cell@
        CellGroupData[
          Prepend[Cell["Examples", "Subsection", "ExamplesSection"]]@
          #
          ]&,
      Identity
      ]@Replace[
          ex,
          {
            (a_->b_List):>
              Cell@
                CellGroupData[
                  Prepend[
                    Cell[a, "S"<>StringRepeat["ubs", d+2]<>"ection", "ExamplesSection"]
                    ]@formatExamplesSection[b, d+1],
                  If[dooooop, dooooop=False;Open, Closed]
                  ],
            (a_->b_):>
              Cell@
                CellGroupData[{
                  Cell[a, "Text", "ExamplesText"],
                  Cell[
                    BoxData@FrontEndExecute@
                      FrontEnd`ReparseBoxStructurePacket@b, "Code", "ExamplesInput"]
                  }]
            },
          1
          ]
    ]


(* ::Subsubsubsection::Closed:: *)
(*formatRelatedSection*)



formatRelatedSection[names_]:=
  Cell@CellGroupData[
    {
      Cell@
        CellGroupData[
          {
            Cell["See Also", "Subsection", "SeeAlso"],
            Cell[
              TextData@
                Riffle[
                  ButtonBox[#,
                    BaseStyle->{"Link", "Input"},ButtonData->"paclet:ref/"<>#
                    ]&/@names,
                  " | "
                  ],
               "Text"
              ]
            }
          ],
      $baseTemplates["Related Guides"],
      $baseTemplates["Related Links"]
      }
    ]


(* ::Subsubsubsection::Closed:: *)
(*SymbolNotebookTemplate*)



SymbolNotebookTemplate[s_Symbol]:=
  Module[
    {
      bits,
      use,
      deets,
      exams,
      similar,
      keys,
      meta,
      nb
      },
    keys={"UsageMessages", "Details", "Examples", "RelatedFunctions"};
    bits=GenerateFunctionInfo[s, "Keys"->keys];
    {use, deets, exams, similar}=Lookup[bits, keys];
    use=
      StringSplit[use, 
        k:((StartOfLine|StartOfString)~~a:Except["["]..~~"["~~b__~~"]")/;
          StringCount[b, "["]==StringCount["b", "]"]:>
          k
        ];
    meta=AssociationThread[ToLowerCase@Flatten@Values@$MetadataMap, Automatic];
    meta["label"]=SymbolName[s];
    meta["context"]=Context[s];
    meta["type"]="Symbol";
    nb=
      Notebook[
        {
          $metaCell,
          $miscTemplates["TitleBar"]/.
            "<Context>"->StringDelete[meta["context"], "`"]<>" Symbol",
          Cell[meta["label"], "Section", "SymbolName"],
          formatUsageSection[use],
          formatDetailsSection[deets],
          formatExamplesSection[exams],
          formatRelatedSection[similar],
          $NotebookTemplates["Footer"]
          },
        {
          StyleDefinitions->FrontEnd`FileName[{"SimpleDocs"}, "SimpleDocs.nb"],
          TaggingRules->{
            "Metadata"->DocMetadata@Normal@meta,
            "ColorType"->"SymbolColor"
            },
          ScreenStyleEnvironment->"Editing"
          }
        ]
    ]


(* ::Subsubsection::Closed:: *)
(*GuideNotebookTemplate*)



GuideNotebookTemplate[name_String]:=
  Module[
    {
      cleanName,
      meta,
      nb
      },
    meta=AssociationThread[ToLowerCase@Flatten@Values@$MetadataMap, Automatic];
    cleanName=StringDelete[name, Except[WordCharacter]|"$"];
    meta["label"]=cleanName;
    meta["type"]="Guide";
    nb=
      Notebook[
        {
          $metaCell,
          $miscTemplates["TitleBar"]/.
            "<Context>"->"Guide",
          Cell[name, "Section", "GuideName"],
          Cell["guide descriptions", "Text"],
          $sectionTemplates["Guide Section"],
          $miscTemplates["Divider"],
          $NotebookTemplates["Related Guides"],
          $NotebookTemplates["Related Links"],
          $NotebookTemplates["Footer"]
          },
        {
          StyleDefinitions->FrontEnd`FileName[{"SimpleDocs"}, "SimpleDocs.nb"],
          TaggingRules->{
            "Metadata"->DocMetadata@Normal@meta,
            "ColorType"->"GuideColor"
            },
          ScreenStyleEnvironment->"Editing"
          }
        ]
    ]


(* ::Subsubsection::Closed:: *)
(*TutorialNotebookTemplate*)



TutorialNotebookTemplate[name_String]:=
  Module[
    {
      cleanName,
      meta,
      nb
      },
    meta=AssociationThread[ToLowerCase@Flatten@Values@$MetadataMap, Automatic];
    cleanName=StringDelete[name, Except[WordCharacter]|"$"];
    meta["label"]=cleanName;
    meta["type"]="Tutorial";
    nb=
      Notebook[
        {
          $metaCell,
          $miscTemplates["TitleBar"]/.
            "<Context>"->"Tutorial",
          Cell[name, "Section", "TutorialName"],
          Cell["Tutorial text...", "Text"],
          $miscTemplates["Divider"],
          $NotebookTemplates["Related Guides"],
          $NotebookTemplates["Related Links"],
          $NotebookTemplates["Footer"]
          },
        {
          StyleDefinitions->FrontEnd`FileName[{"SimpleDocs"}, "SimpleDocs.nb"],
          TaggingRules->{
            "Metadata"->DocMetadata@Normal@meta,
            "ColorType"->"TutorialColor"
            },
          ScreenStyleEnvironment->"Editing"
          }
        ]
    ]


(* ::Subsubsection::Closed:: *)
(*SampleTemplateNotebook*)



(* ::Subsubsubsection::Closed:: *)
(*Symbol*)



SampleTemplateNotebook["Symbol"]:=
  Block[{SamplePaclet`Sym, SamplePaclet`Sym1, SamplePaclet`Sym2},
    SamplePaclet`Sym::usage="sample function";
    SamplePaclet`Sym::msg="sample message";
    SamplePaclet`Sym[arg_]:=Null;
    SamplePaclet`Sym~SetAttributes~Temporary;
    SamplePaclet`Sym1=1;
    SamplePaclet`Sym2=2;
    CreateTemplateNotebook["Symbol", SamplePaclet`Sym]
    ]


(* ::Subsubsubsection::Closed:: *)
(*Guide*)



SampleTemplateNotebook["Guide"]:=
  CreateTemplateNotebook["Guide", "Sample Guide"];


(* ::Subsubsubsection::Closed:: *)
(*Tutorial*)



SampleTemplateNotebook["Tutorial"]:=
  CreateTemplateNotebook["Tutorial", "Sample Tutorial"];


(* ::Subsection:: *)
(*GUI*)



(* ::Subsubsection::Closed:: *)
(*$MetadataEditor*)



(* ::Subsubsubsection::Closed:: *)
(*boxGrid*)



boxGrid=
Column[
KeyValueMap[
OpenerView[
{#, 
Grid[
Map[
{#,
With[{tag=ToLowerCase@StringDelete[#, " "]},
InputField[
Dynamic@CurrentValue[EvaluationNotebook[], {TaggingRules,"Metadata", tag}, Automatic]
]
]
}&,
#2
],
Alignment->Left
]
}
]&,
$MetadataMap
]
];


(* ::Subsubsubsection::Closed:: *)
(*showButton*)



hideButton[Hold[var_]]:=
  Button["",
    var=False, 
    ImageSize->{7, 7},
    FrameMargins->0,
    ImageMargins->0,
    Appearance->
      {
        "Default"->
          Image[ToExpression[FrontEndResource["FEBitmaps", "SquareMinusIconSmall"]]]
        }
    ]


showButton[Hold[var_]]:=
  Button["",
    var=True, 
    ImageSize->{7, 7},
    FrameMargins->0,
    ImageMargins->0,
    Appearance->
      {
        "Default"->
          Image[ToExpression[FrontEndResource["FEBitmaps", "SquarePlusIconSmall"]]]
        }
    ]


(* ::Subsubsubsection::Closed:: *)
(*$MetadataEditor*)



$MetadataEditor=
  DynamicModule[{show},
    With[
      {
        bg=boxGrid, 
        hb=hideButton[Hold@show], sb=showButton[Hold@show]
        },
      Dynamic@
        Grid[
          {
            {
              If[TrueQ@show, hb, sb], 
              Item["Metadata", ItemSize->Scaled[.15]],
              Item[
                ButtonBar[
                  {
                    "Populate":>
                      (
                        Needs["SimpleDocs`"];
                        PopulateNotebookMetadata[EvaluationNotebook[]]
                        ),
                    "Clear":>
                      (
                        Needs["SimpleDocs`"];
                        ClearNotebookMetadata[EvaluationNotebook[]]
                        )
                    },
                  ImageSize->{100, Automatic}
                  ],
                Alignment->Right,
                ItemSize->Scaled[.8]
                ]
              },
            {Null, If[TrueQ@show, bg], SpanFromLeft}
            },
          Alignment->Left
          ]
      ]
    ];


(* ::Subsubsection::Closed:: *)
(*$InsertionMenu*)



(* ::Subsubsubsection::Closed:: *)
(*$insertTemplate*)



$insertionMenuTemplates=
  Join@@
    Replace[
      Riffle[
        KeyValueMap[
          #:>NotebookWrite[InputNotebook[], #2]&,
          #
          ]&/@{
          $primaryTemplates,
          $sectionTemplates,
          $baseTemplates,
          $miscTemplates
          },
        Delimiter
        ],
      Delimiter->{Delimiter},
      1
      ]


(* ::Subsubsubsection::Closed:: *)
(*$InsertionMenu*)



$thumb1=
  RawBoxes@
    DynamicBox[
      FEPrivate`ImportImage[
        FrontEnd`FileName[
          {"Misc"},
          "CellInsertionPointBitmap.png"
          ]
        ]
      ];


$thumb2=
  Pane[
    Framed[
      Style["+", Large, Gray], 
      Background->GrayLevel[.95], 
      FrameStyle->Gray, 
      RoundingRadius->5,
      ImageSize->{80, 40},
      FrameMargins->{{25, 25}, {5, 5}},
      Alignment->Center
      ],
    {80, 26},
    Alignment->{Left, Top},
    BaselinePosition->Bottom,
    ImageSizeAction->"Clip",
    ScrollPosition->{150, 50},
    Scrollbars->False
    ];


$InsertionMenu=
  ActionMenu[
    $thumb2,
    $insertionMenuTemplates,
    Appearance->None
    ]


(* ::Subsubsection::Closed:: *)
(*$HamburgerMenu*)



$HamburgerMenu=
  ActionMenu[
    Button["\[Congruent]",None,Appearance->None, ImageSize->{50, 35}],
    {
      "Save Documentation":>
        (
          Needs["SimpleDocs`"];
          NotebookOpen@SaveNotebookToDocumentation[EvaluationNotebook[]]
          ),
      "Save To Project":>
        (
          Needs["SimpleDocs`"];
          SaveNotebookToProject[EvaluationNotebook[]]
          ),
      "Save Markdown":>
        (
          Needs["SimpleDocs`"];
          NotebookOpen@SaveNotebookMarkdown[EvaluationNotebook[]]
          ),
      Delimiter,
      "Set Paclet":>
        (
          Needs["SimpleDocs`"];
          SetNotebookPaclet[EvaluationNotebook[]]
          ),
      "Update PacletInfo":>
        (
          Needs["SimpleDocs`"];
          Replace[SetPacletInfo[EvaluationNotebook[]],
            s_String:>NotebookOpen@s
            ]
          ),
      Delimiter,
      "New Symbol":>
        (
          Needs["SimpleDocs`"];
          SampleTemplateNotebook["Symbol"]
          ),
      "New Guide":>
        (
          Needs["SimpleDocs`"];
          SampleTemplateNotebook["Guide"]
          ),
      "New Tutorial":>
        (
          Needs["SimpleDocs`"];
          SampleTemplateNotebook["Tutorial"]
          ),
      Delimiter,
      "Open SiteConfig":>
        (
          Needs["SimpleDocs`"];
          OpenDocsSiteConfig[EvaluationNotebook[]]
          ),
      "Build Site":>
        (
          Needs["SimpleDocs`"];
          BuildNotebookDocsSite[EvaluationNotebook[]]
          )
      },
    Appearance->None,
    Method->"Queued"
    ];


(* ::Subsubsection::Closed:: *)
(*$AutosaveButtons*)



$AutosaveButtons=
  Style[#, PageWidth->Infinity]&@
  Grid[
    {
      {Item["Save", Alignment->Left], SpanFromLeft},
      {Null,
        Item[
          Grid[
          {
            {
              ".md:",
              Checkbox[
                Dynamic@
                  CurrentValue[
                    EvaluationNotebook[], 
                    {TaggingRules, "SimpleDocs", "MarkdownAutosave"},
                    False
                    ]
                ]
              },
            {
              ".nb:",
              Checkbox[
                Dynamic@
                  CurrentValue[
                    EvaluationNotebook[], 
                    {TaggingRules, "SimpleDocs", "DocumentationAutosave"},
                    False
                    ]
                ]
              }
            },
          Spacings->{0, -.1}
          ],
        Alignment->Right
        ]
        }
      }
    ]


(* ::Subsubsection::Closed:: *)
(*$DockedCell*)



$dockedCell=
  Grid[
    {
      {
        Item[
          Framed[
            $MetadataEditor, 
            ImageSize->{Scaled[1], {55, 1000}},
            Background->White,
            RoundingRadius->5,
            BaseStyle->"Panel",
            FrameStyle->GrayLevel[.8]
            ], 
          ItemSize->{Scaled[.7], Automatic}
          ], 
        Item["", ItemSize->Scaled[.15]],
        Item[
          Pane[$AutosaveButtons,
            {Scaled[1], 50},
            Alignment->{Right, Top},
            ImageSizeAction->"ShrinkToFit"
            ],
          ItemSize->{Scaled[.1], All},
          Alignment->{Right, Top}
          ],
        Item[$HamburgerMenu(*ItemSize\[Rule]Scaled[.03]*),Alignment->Right]
        }
      }, 
    Alignment->{Left, Top}, 
    BaseStyle->{FontFamily->"Helvetica", FontSize->14}
    ];


$DockedCell=
  {
    Cell[
      BoxData[ToBoxes@$dockedCell],
      "Output",
      Background->GrayLevel[.95],
      CellFrameColor->Gray,
      CellFrame->{{0, 0}, {1, 0}}
      ],
    Cell[
      BoxData@ToBoxes@$InsertionMenu,
      "Output",
      Background->None,
      TextAlignment->Center,
      CellFrame->None,
      CellMargins->
        {
          {
            FEPrivate`Part[
              FrontEnd`AbsoluteCurrentValue[WindowSize],
              1
              ]-120, 
            35
            }, 
          {0, -2}
          }
      ]
    }


(* ::Subsection:: *)
(*Paclets*)



(* ::Text:: *)
(*
	Not sure how best to fit this into the whole new \[OpenCurlyDoubleQuote]project\[CloseCurlyDoubleQuote] structure. There might not always be a paclet to anchor to?
*)



SetPacletInfo//Clear
SetPacletInfo[pac:_String|_PacletManager`Paclet]:=
  Module[{pi=PacletManager`PacletInformation@pac},
    PacletExecute["GeneratePacletInfo",
      Lookup[pi, "Location"],
      "Version"->Lookup[pi, "Version"]
      ]
    ];
SetPacletInfo[nb_NotebookObject, ploc_:Automatic]:=
  Module[{pac=getNotebookPaclet[nb, ploc]},
    SetPacletInfo[pac]
    ];


End[];



