Paclet[
  Name -> "Ems",
  Version -> "1.0.5",
  Extensions -> {
    	{
     		"Kernel",
     		"Root" -> ".",
     		"Context" -> {"Ems`"}
     	},
    	{"FrontEnd"},
    	{
     		"Resource",
     		"Root" -> "Resources",
     		"Resources" -> {
       			"Icons",
       			"Templates",
       			"Themes",
       			{
        				"banner",
        				"Icons/banner.png"
        			},
       			{
        				"banner_tall",
        				"Icons/banner_tall.png"
        			},
       			{
        				"EmsIcon",
        				"Icons/EmsIcon.png"
        			},
       			{
        				"favicon-16x16",
        				"Icons/favicon-16x16.png"
        			},
       			{
        				"favicon-32x32",
        				"Icons/favicon-32x32.png"
        			},
       			{
        				"SiteConfig",
        				"Templates/blog/SiteConfig.wl"
        			},
       			{
        				"blog",
        				"Templates/blog"
        			},
       			{
        				"content",
        				"Templates/blog/content"
        			},
       			{
        				"docs",
        				"Templates/docs"
        			},
       			{
        				"portfolio",
        				"Templates/portfolio"
        			},
       			{
        				"scroll",
        				"Templates/scroll"
        			},
       			{
        				"bootstrap-blog",
        				"Themes/bootstrap-blog"
        			},
       			{
        				"static",
        				"Themes/bootstrap-blog/static"
        			},
       			{
        				"templates",
        				"Themes/bootstrap-blog/templates"
        			},
       			{
        				"bootstrap-docs",
        				"Themes/bootstrap-docs"
        			},
       			{
        				"bootstrap-portfolio",
        				"Themes/bootstrap-portfolio"
        			},
       			{
        				"bootstrap-single-page",
        				"Themes/bootstrap-single-page"
        			}
       		}
     	}
    }
 ]